//// Actions for searching a Doctor

export const SEARCH_DOCTOR_REQUEST = 'SEARCH_DOCTOR_REQUEST'
export const SEARCH_DOCTOR_SUCCESS = 'SEARCH_DOCTOR_SUCCESS'
export const SEARCH_DOCTOR_FAILURE = 'SEARCH_DOCTOR_FAILURE'